/* automatically generated by rust-bindgen 0.63.0 */

extern "C" {
    pub fn VpuDetectAvcc(
        pCodecData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_uint,
        pIsAvcc: *mut ::core::ffi::c_int,
        pNalSizeLength: *mut ::core::ffi::c_int,
        pNalNum: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuDetectHvcc(
        pCodecData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_uint,
        pIsHvcc: *mut ::core::ffi::c_int,
        pNalSizeLength: *mut ::core::ffi::c_int,
        pNalNum: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuConvertAvccHeader(
        pCodecData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_uint,
        ppOut: *mut *mut ::core::ffi::c_uchar,
        pOutSize: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuConvertHvccHeader(
        pCodecData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_uint,
        ppOut: *mut *mut ::core::ffi::c_uchar,
        pOutSize: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuConvertAvccFrame(
        pData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_uint,
        nNalSizeLength: ::core::ffi::c_int,
        ppFrm: *mut *mut ::core::ffi::c_uchar,
        pSize: *mut ::core::ffi::c_uint,
        pNalNum: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VC1CreateNALSeqHeader(
        pHeader: *mut ::core::ffi::c_uchar,
        pHeaderLen: *mut ::core::ffi::c_int,
        pCodecPri: *mut ::core::ffi::c_uchar,
        nCodecSize: ::core::ffi::c_int,
        pData: *mut ::core::ffi::c_uint,
        nMaxHeader: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VC1CreateRCVSeqHeader(
        pHeader: *mut ::core::ffi::c_uchar,
        pHeaderLen: *mut ::core::ffi::c_int,
        pCodecPri: *mut ::core::ffi::c_uchar,
        nFrameSize: ::core::ffi::c_uint,
        nWidth: ::core::ffi::c_int,
        nHeight: ::core::ffi::c_int,
        pNoError: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VC1CreateNalFrameHeader(
        pHeader: *mut ::core::ffi::c_uchar,
        pHeaderLen: *mut ::core::ffi::c_int,
        pInData: *mut ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VC1CreateRCVFrameHeader(
        pHeader: *mut ::core::ffi::c_uchar,
        pHeaderLen: *mut ::core::ffi::c_int,
        nInSize: ::core::ffi::c_uint,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuFindAVCStartCode(
        pData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_int,
        ppStart: *mut *mut ::core::ffi::c_uchar,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuConvertToAvccData(
        pData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn VpuConvertToAvccHeader(
        pData: *mut ::core::ffi::c_uchar,
        nSize: ::core::ffi::c_int,
        pFilledSize: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
